"""Use-case orchestration built on the domain and ports layers."""

from .baseline import (
    DEFAULT_LOGICAL_BLOCK_ACCURACY_THRESHOLD,
    DEFAULT_SOURCE_BASELINE_COMPONENT_MINIMA,
    DEFAULT_SOURCE_BASELINE_THRESHOLD,
    DEFAULT_STRUCTURE_MATCH_THRESHOLD,
    SOURCE_BASELINE_COMPONENT_WEIGHTS,
    SOURCE_BASELINE_EVALUATOR_NAME,
    SOURCE_BASELINE_EVALUATOR_VERSION,
    SourceBaselineConfig,
    evaluate_source_baseline,
    normalize_source_text,
    source_character_accuracy,
)
from .extract import (
    EXTRACTION_PROVIDER,
    EXTRACTION_PROVIDER_VERSION,
    PAGE_COVERING_IMAGE_FRACTION,
    ExtractionDiagnostic,
    PngExtractionError,
    PngExtractionResult,
    extract_png,
)
from .evaluate import (
    COMPONENT_WEIGHTS,
    DEFAULT_RESTORATION_THRESHOLD,
    EVALUATOR_NAME,
    EVALUATOR_VERSION,
    GEOMETRY_CENTER_WEIGHT,
    GEOMETRY_IOU_WEIGHT,
    MIN_TEXT_ELEMENT_SIMILARITY,
    EvaluationConfig,
    build_evaluation_reference,
    evaluate_restoration,
    evaluate_restoration_input,
    normalize_evaluation_text,
)
from .preview import render_preview
from .render import render_docx

__all__ = [
    "DEFAULT_LOGICAL_BLOCK_ACCURACY_THRESHOLD",
    "DEFAULT_SOURCE_BASELINE_COMPONENT_MINIMA",
    "DEFAULT_SOURCE_BASELINE_THRESHOLD",
    "DEFAULT_STRUCTURE_MATCH_THRESHOLD",
    "EXTRACTION_PROVIDER",
    "EXTRACTION_PROVIDER_VERSION",
    "PAGE_COVERING_IMAGE_FRACTION",
    "ExtractionDiagnostic",
    "COMPONENT_WEIGHTS",
    "DEFAULT_RESTORATION_THRESHOLD",
    "EVALUATOR_NAME",
    "EVALUATOR_VERSION",
    "EvaluationConfig",
    "GEOMETRY_CENTER_WEIGHT",
    "GEOMETRY_IOU_WEIGHT",
    "MIN_TEXT_ELEMENT_SIMILARITY",
    "SOURCE_BASELINE_COMPONENT_WEIGHTS",
    "SOURCE_BASELINE_EVALUATOR_NAME",
    "SOURCE_BASELINE_EVALUATOR_VERSION",
    "SourceBaselineConfig",
    "PngExtractionError",
    "PngExtractionResult",
    "extract_png",
    "build_evaluation_reference",
    "evaluate_restoration",
    "evaluate_restoration_input",
    "evaluate_source_baseline",
    "normalize_evaluation_text",
    "normalize_source_text",
    "render_docx",
    "render_preview",
    "source_character_accuracy",
]
