"""Use-case orchestration built on the domain and ports layers."""

from .baseline import (
    DEFAULT_LOGICAL_BLOCK_ACCURACY_THRESHOLD,
    DEFAULT_SOURCE_BASELINE_COMPONENT_MINIMA,
    DEFAULT_SOURCE_BASELINE_THRESHOLD,
    DEFAULT_STRUCTURE_MATCH_THRESHOLD,
    SOURCE_BASELINE_COMPONENT_WEIGHTS,
    SOURCE_BASELINE_EVALUATOR_NAME,
    SOURCE_BASELINE_EVALUATOR_VERSION,
    SourceBaselineConfig,
    evaluate_source_baseline,
    normalize_source_text,
    source_character_accuracy,
)
from .extract import (
    EXTRACTION_PROVIDER,
    EXTRACTION_PROVIDER_VERSION,
    PAGE_COVERING_IMAGE_FRACTION,
    ExtractionDiagnostic,
    PngExtractionError,
    PngExtractionResult,
    extract_png,
)
from .evaluate import (
    COMPONENT_WEIGHTS,
    DEFAULT_RESTORATION_THRESHOLD,
    EVALUATOR_NAME,
    EVALUATOR_VERSION,
    GEOMETRY_CENTER_WEIGHT,
    GEOMETRY_IOU_WEIGHT,
    MIN_TEXT_ELEMENT_SIMILARITY,
    EvaluationConfig,
    build_docx_structure_relationships,
    build_evaluation_reference,
    evaluate_restoration,
    evaluate_restoration_input,
    normalize_evaluation_text,
)
from .ocr_quality import (
    DEFAULT_LOW_CONFIDENCE_THRESHOLD,
    DEFAULT_MINIMUM_LOGICAL_BLOCK_COVERAGE,
    DEFAULT_MINIMUM_TEXT_ACCURACY,
    DEFAULT_REQUIRED_ANCHOR_RECALL,
    OCR_QUALITY_EVALUATOR_NAME,
    OCR_QUALITY_EVALUATOR_VERSION,
    OcrQualityConfig,
    evaluate_ocr_quality,
    normalize_ocr_text,
    ocr_character_accuracy,
)
from .ocr_experiment import compare_ocr_experiment
from .ocr_resolution import (
    DEFAULT_MINIMUM_TEXT_ACCURACY_DELTA,
    OCR_RESOLUTION_EVALUATOR_NAME,
    OCR_RESOLUTION_EVALUATOR_VERSION,
    compare_ocr_resolution,
)
from .preview import render_preview
from .render import render_docx
from .table_topology import (
    TABLE_TOPOLOGY_BOUNDARY_TOLERANCE_PT,
    TABLE_TOPOLOGY_PARAMETERS_DIGEST,
    infer_table_topology,
)

__all__ = [
    "DEFAULT_LOGICAL_BLOCK_ACCURACY_THRESHOLD",
    "DEFAULT_SOURCE_BASELINE_COMPONENT_MINIMA",
    "DEFAULT_SOURCE_BASELINE_THRESHOLD",
    "DEFAULT_STRUCTURE_MATCH_THRESHOLD",
    "EXTRACTION_PROVIDER",
    "EXTRACTION_PROVIDER_VERSION",
    "PAGE_COVERING_IMAGE_FRACTION",
    "ExtractionDiagnostic",
    "COMPONENT_WEIGHTS",
    "DEFAULT_RESTORATION_THRESHOLD",
    "DEFAULT_LOW_CONFIDENCE_THRESHOLD",
    "DEFAULT_MINIMUM_LOGICAL_BLOCK_COVERAGE",
    "DEFAULT_MINIMUM_TEXT_ACCURACY",
    "DEFAULT_REQUIRED_ANCHOR_RECALL",
    "EVALUATOR_NAME",
    "EVALUATOR_VERSION",
    "EvaluationConfig",
    "GEOMETRY_CENTER_WEIGHT",
    "GEOMETRY_IOU_WEIGHT",
    "MIN_TEXT_ELEMENT_SIMILARITY",
    "OCR_QUALITY_EVALUATOR_NAME",
    "OCR_QUALITY_EVALUATOR_VERSION",
    "OcrQualityConfig",
    "DEFAULT_MINIMUM_TEXT_ACCURACY_DELTA",
    "OCR_RESOLUTION_EVALUATOR_NAME",
    "OCR_RESOLUTION_EVALUATOR_VERSION",
    "SOURCE_BASELINE_COMPONENT_WEIGHTS",
    "SOURCE_BASELINE_EVALUATOR_NAME",
    "SOURCE_BASELINE_EVALUATOR_VERSION",
    "SourceBaselineConfig",
    "TABLE_TOPOLOGY_BOUNDARY_TOLERANCE_PT",
    "TABLE_TOPOLOGY_PARAMETERS_DIGEST",
    "PngExtractionError",
    "PngExtractionResult",
    "extract_png",
    "build_docx_structure_relationships",
    "build_evaluation_reference",
    "evaluate_restoration",
    "evaluate_restoration_input",
    "evaluate_ocr_quality",
    "compare_ocr_experiment",
    "compare_ocr_resolution",
    "evaluate_source_baseline",
    "infer_table_topology",
    "normalize_evaluation_text",
    "normalize_ocr_text",
    "normalize_source_text",
    "render_docx",
    "render_preview",
    "source_character_accuracy",
    "ocr_character_accuracy",
]
