"""Protocols implemented by Aiteqno infrastructure adapters."""

from .assets import AssetResolutionError, AssetResolver, ResolvedAsset
from .docx import (
    DocxRenderError,
    DocxRenderer,
    DocxRenderReport,
    DocxRenderResult,
    FontSubstitution,
    RenderPolicy,
    RenderWarning,
)
from .extraction import (
    AssetEncodingError,
    AssetPayload,
    BundleWriteError,
    BundleWriteResult,
    DocumentBundleWriter,
    DocumentIRSchemaError,
    DocumentIRValidator,
    EncodedImageAsset,
    ImageAssetEncoder,
)
from .ocr import (
    DEFAULT_OCR_LANGUAGES,
    OcrBackend,
    OcrBackendError,
    OcrCapabilities,
    OcrOptions,
    OcrRegion,
    OcrToken,
)
from .preview import (
    PreviewFontSubstitution,
    PreviewRenderer,
    PreviewRenderError,
    PreviewRenderReport,
    PreviewRenderResult,
    PreviewWarning,
)
from .structure import (
    ImageInput,
    LineCandidate,
    LineOrientation,
    PageCandidate,
    PixelMode,
    PixelPoint,
    PngDecoder,
    RectangleCandidate,
    RegionCandidate,
    RegionKind,
    StructureExtractionError,
    StructureExtractionResult,
    StructureExtractor,
)

__all__ = [
    "AssetResolutionError",
    "AssetResolver",
    "AssetEncodingError",
    "AssetPayload",
    "BundleWriteError",
    "BundleWriteResult",
    "DocxRenderError",
    "DocxRenderer",
    "DocxRenderReport",
    "DocxRenderResult",
    "DocumentBundleWriter",
    "DocumentIRSchemaError",
    "DocumentIRValidator",
    "DEFAULT_OCR_LANGUAGES",
    "FontSubstitution",
    "EncodedImageAsset",
    "ImageInput",
    "ImageAssetEncoder",
    "LineCandidate",
    "LineOrientation",
    "OcrBackend",
    "OcrBackendError",
    "OcrCapabilities",
    "OcrOptions",
    "OcrRegion",
    "OcrToken",
    "PageCandidate",
    "PixelMode",
    "PixelPoint",
    "PngDecoder",
    "PreviewFontSubstitution",
    "PreviewRenderer",
    "PreviewRenderError",
    "PreviewRenderReport",
    "PreviewRenderResult",
    "PreviewWarning",
    "RectangleCandidate",
    "RegionCandidate",
    "RegionKind",
    "RenderPolicy",
    "RenderWarning",
    "ResolvedAsset",
    "StructureExtractionError",
    "StructureExtractionResult",
    "StructureExtractor",
]
