"""Protocols implemented by Aiteqno infrastructure adapters."""

from .assets import AssetResolutionError, AssetResolver, ResolvedAsset
from .docx import (
    DocxRenderError,
    DocxRenderer,
    DocxRenderReport,
    DocxRenderResult,
    FontSubstitution,
    RenderPolicy,
    RenderWarning,
)
from .preview import (
    PreviewFontSubstitution,
    PreviewRenderer,
    PreviewRenderError,
    PreviewRenderReport,
    PreviewRenderResult,
    PreviewWarning,
)
from .structure import (
    ImageInput,
    LineCandidate,
    LineOrientation,
    PageCandidate,
    PixelMode,
    PixelPoint,
    PngDecoder,
    RectangleCandidate,
    RegionCandidate,
    RegionKind,
    StructureExtractionError,
    StructureExtractionResult,
    StructureExtractor,
)

__all__ = [
    "AssetResolutionError",
    "AssetResolver",
    "DocxRenderError",
    "DocxRenderer",
    "DocxRenderReport",
    "DocxRenderResult",
    "FontSubstitution",
    "ImageInput",
    "LineCandidate",
    "LineOrientation",
    "PageCandidate",
    "PixelMode",
    "PixelPoint",
    "PngDecoder",
    "PreviewFontSubstitution",
    "PreviewRenderer",
    "PreviewRenderError",
    "PreviewRenderReport",
    "PreviewRenderResult",
    "PreviewWarning",
    "RectangleCandidate",
    "RegionCandidate",
    "RegionKind",
    "RenderPolicy",
    "RenderWarning",
    "ResolvedAsset",
    "StructureExtractionError",
    "StructureExtractionResult",
    "StructureExtractor",
]
